export function getRandomTaskQuote() {
    const quotes = [
        "🚀 Great achievements start with a well-organized plan. Prioritize, execute, and succeed!",
        "⚡ Productivity is not about being busy, it's about being effective. Organize your tasks wisely!",
        "📈 Small, consistent actions lead to big results. Plan your tasks, and progress will follow!",
        "🎯 A goal without a plan is just a wish. Structure your tasks and turn dreams into reality!",
        "🕒 Discipline beats motivation. Stick to your schedule, tackle your tasks, and win the day!",
        "💡 Success is built daily. Focus on completing one task at a time, and the results will amaze you!",
        "📝 Don't let tasks overwhelm you—break them into steps and handle them one at a time!",
        "🧹 An unfinished task is mental clutter. Clear your mind by finishing what you start!",
        "⏳ If it takes less than 5 minutes, do it now! Small wins lead to big victories!",
        "🔥 The best way to get things done is to begin. Start now, and momentum will follow!",
        "✅ Every task completed is a step closer to your goal. Stay focused and keep moving forward!",
        "🏆 Your future success depends on today’s actions. Plan, execute, and grow!",
        "📌 Prioritize what matters most. Not all tasks are created equal—focus on impact!",
        "🛑 Stop overthinking. Start doing. Action beats perfection every single time!",
        "🛠️ Break complex projects into small tasks. One step at a time leads to massive success!",
        "📅 A well-organized to-do list is the roadmap to achievements!",
        "🧭 Master your schedule, master your life. Time management is the key to greatness!",
        "💪 Don't be busy, be productive. Work smart, and let efficiency guide you!",
        "🚫 Procrastination steals your future. Take control, act now, and own your success!",
        "🧘 A cluttered task list is a cluttered mind. Organize your tasks, and clarity will follow!",
        "🔝 Tackle the hardest task first. Once it's done, everything else feels easier!",
        "🏗️ Your tasks are the building blocks of your future. Lay them down wisely!",
        "📊 Success is a sum of small efforts repeated daily. Stay disciplined!",
        "🔮 The best way to predict your future is to create it—one task at a time!",
        "⌛ Don’t wait for the perfect moment. Start with what you have, where you are!",
        "⏰ Time wasted is life wasted. Plan your day, prioritize tasks, and make every second count!",
        "🎖️ Stay committed to your tasks. Every completed task is a win, no matter how small!",
        "🎢 Momentum starts with action. Begin your first task, and the rest will follow!",
        "🌱 Consistency beats intensity. Show up, complete tasks, and let success unfold!",
        "🔄 You don't need more time; you need better time management. Organize and execute!",
        "📌 Progress is progress, no matter how small. Keep ticking off your tasks!",
        "🚦 Don’t let distractions steal your focus. Set clear goals and get things done!",
        "🏁 Focus on completing, not just starting. A finished task is worth more than a thousand ideas!",
        "📅 Good things come to those who schedule them. Plan your tasks, and make things happen!",
        "🌙 A productive day is built the night before. Plan ahead and set yourself up for success!",
        "💯 You are what you repeatedly do. Make task management a habit, and success will follow!",
        "⚖️ Work expands to fill the time available. Set deadlines and get things done faster!",
        "🎯 Your time is your most valuable resource. Spend it wisely on tasks that truly matter!",
        "🚀 Don’t let your tasks control you. Take charge, prioritize, and own your day!",
        "🟢 The power of now: Stop postponing, start acting, and watch progress unfold!",
        "🛠️ Start where you are, use what you have, and do what you can. No excuses—just action!",
        "🏅 Each small completed task brings you closer to success. Keep going!",
        "📌 A well-executed plan is better than a perfect idea. Organize, execute, and succeed!",
        "⚡ The key to productivity is starting. Begin now, and momentum will carry you forward!",
        "🎯 Done is better than perfect. Complete tasks, improve over time, and keep progressing!",
        "🗂️ Plan your work, then work your plan. Stay disciplined, and success is inevitable!",
        "🔑 Your future is shaped by what you do today. Get started on your tasks now!",
        "🔕 Remove distractions, focus deeply, and watch your productivity skyrocket!",
        "📆 If you fail to plan, you plan to fail. Structure your tasks and win the day!",
        "⏭️ Your daily tasks define your future success. Be intentional with your time!",
        "🚀 The faster you complete tasks, the more freedom you create for yourself!",
        "📝 Your mind is for creating ideas, not storing tasks. Write them down and execute!",
        "🏗️ A goal well planned is a goal half achieved. Organize first, then take action!",
        "🔍 Think big but execute small. Each completed task leads to massive success!",
        "📋 Don’t let unfinished tasks pile up. Stay on top of them and maintain momentum!",
        "⚡ The best productivity hack? Just start! Action leads to motivation!",
        "🏆 Make every task count. Focus on what moves the needle the most!",
        "🛤️ A well-structured to-do list turns chaos into clarity. Organize before you execute!",
        "🔄 Your success is in your daily routine. Plan, execute, and keep refining!"
    ];

    // Return a random quote
    return quotes[Math.floor(Math.random() * quotes.length)];
}
